from __future__ import annotations

import argparse
from datetime import UTC, datetime
import json
from pathlib import Path
from typing import Any

import joblib
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import mutual_info_classif
from sklearn.impute import SimpleImputer
from sklearn.inspection import permutation_importance
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    average_precision_score,
    f1_score,
    precision_recall_curve,
    precision_score,
    recall_score,
    roc_auc_score,
)
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Train and select a churn model for SliceIQ."
    )
    parser.add_argument(
        "--input",
        default="ml/data/churn_training_dataset.csv",
        help="Training dataset generated by churn_build_dataset.py",
    )
    parser.add_argument(
        "--model-output",
        default="ml/models/churn_reorder_model.joblib",
        help="Model artifact path.",
    )
    parser.add_argument(
        "--metrics-output",
        default="ml/models/churn_reorder_metrics.json",
        help="Training metrics JSON path.",
    )
    parser.add_argument(
        "--feature-importance-output",
        default="ml/models/churn_feature_importance.csv",
        help="Feature importance CSV path.",
    )
    parser.add_argument(
        "--drift-baseline-output",
        default="ml/models/churn_drift_baseline.json",
        help="Baseline score distribution for production monitoring.",
    )
    parser.add_argument(
        "--max-features",
        type=int,
        default=18,
        help="Max features kept after feature selection.",
    )
    return parser.parse_args()


def safe_roc_auc(y_true: pd.Series, y_score: np.ndarray) -> float:
    if y_true.nunique() < 2:
        return 0.5
    return float(roc_auc_score(y_true, y_score))


def safe_pr_auc(y_true: pd.Series, y_score: np.ndarray) -> float:
    return float(average_precision_score(y_true, y_score))


def compute_threshold(y_true: pd.Series, y_score: np.ndarray) -> float:
    precision, recall, thresholds = precision_recall_curve(y_true, y_score)
    if len(thresholds) == 0:
        return 0.5
    f1_values = 2 * precision[:-1] * recall[:-1] / (precision[:-1] + recall[:-1] + 1e-12)
    best_idx = int(np.nanargmax(f1_values))
    return float(thresholds[best_idx])


def split_by_snapshot(df: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    unique_dates = sorted(df["snapshot_date"].dropna().unique().tolist())
    if len(unique_dates) < 3:
        raise RuntimeError(
            "Need at least 3 snapshot dates for time-based train/val/test split."
        )

    n_dates = len(unique_dates)
    train_end = max(1, int(n_dates * 0.6))
    val_end = max(train_end + 1, int(n_dates * 0.8))

    # Keep at least one snapshot for validation and test.
    if val_end >= n_dates:
        val_end = n_dates - 1
    if train_end >= val_end:
        train_end = max(1, val_end - 1)

    train_dates = set(unique_dates[:train_end])
    val_dates = set(unique_dates[train_end:val_end])
    test_dates = set(unique_dates[val_end:])
    if not val_dates or not test_dates:
        raise RuntimeError("Failed to build non-empty validation/test splits from snapshot dates.")

    train_df = df[df["snapshot_date"].isin(train_dates)].copy()
    val_df = df[df["snapshot_date"].isin(val_dates)].copy()
    test_df = df[df["snapshot_date"].isin(test_dates)].copy()
    return train_df, val_df, test_df


def select_features(
    X_train: pd.DataFrame,
    y_train: pd.Series,
    X_val: pd.DataFrame,
    y_val: pd.Series,
    *,
    max_features: int,
) -> list[str]:
    imputer = SimpleImputer(strategy="median")
    X_train_imp = imputer.fit_transform(X_train)
    X_val_imp = imputer.transform(X_val)

    mi = mutual_info_classif(X_train_imp, y_train, random_state=42)
    mi_scores = pd.Series(mi, index=X_train.columns).sort_values(ascending=False)
    top_k = max(8, min(max_features * 2, len(mi_scores)))
    candidate_features = mi_scores.head(top_k).index.tolist()

    rf = RandomForestClassifier(
        n_estimators=400,
        max_depth=8,
        min_samples_leaf=8,
        random_state=42,
        n_jobs=-1,
        class_weight="balanced_subsample",
    )
    rf.fit(X_train_imp[:, [X_train.columns.get_loc(c) for c in candidate_features]], y_train)

    val_candidate = X_val_imp[:, [X_train.columns.get_loc(c) for c in candidate_features]]
    perm = permutation_importance(
        rf,
        val_candidate,
        y_val,
        n_repeats=8,
        random_state=42,
        scoring="average_precision",
        n_jobs=-1,
    )
    perm_scores = pd.Series(perm.importances_mean, index=candidate_features).sort_values(ascending=False)

    selected = perm_scores[perm_scores > 0].index.tolist()
    min_keep = min(6, len(candidate_features))
    if len(selected) < min_keep:
        selected = perm_scores.head(min_keep).index.tolist()

    return selected[:max_features]


def evaluate_predictions(
    y_true: pd.Series,
    y_score: np.ndarray,
    *,
    threshold: float,
) -> dict[str, float]:
    preds = (y_score >= threshold).astype(int)
    return {
        "roc_auc": safe_roc_auc(y_true, y_score),
        "pr_auc": safe_pr_auc(y_true, y_score),
        "accuracy": float(accuracy_score(y_true, preds)),
        "precision": float(precision_score(y_true, preds, zero_division=0)),
        "recall": float(recall_score(y_true, preds, zero_division=0)),
        "f1": float(f1_score(y_true, preds, zero_division=0)),
    }


def get_feature_importance(model: Pipeline, feature_names: list[str]) -> pd.DataFrame:
    clf = model.named_steps["clf"]
    if isinstance(clf, LogisticRegression):
        importance = np.abs(clf.coef_[0])
    elif isinstance(clf, RandomForestClassifier):
        importance = clf.feature_importances_
    else:
        importance = np.zeros(len(feature_names))

    return (
        pd.DataFrame({"feature": feature_names, "importance": importance})
        .sort_values("importance", ascending=False)
        .reset_index(drop=True)
    )


def main() -> None:
    args = parse_args()
    input_path = Path(args.input)
    if not input_path.exists():
        raise FileNotFoundError(
            f"Input dataset not found at {input_path}. Run churn_build_dataset.py first."
        )

    df = pd.read_csv(input_path)
    required_cols = {"user_id", "snapshot_date", "will_order_next_30d"}
    missing_cols = required_cols - set(df.columns)
    if missing_cols:
        raise RuntimeError(f"Training dataset missing required columns: {sorted(missing_cols)}")

    df["snapshot_date"] = pd.to_datetime(df["snapshot_date"], utc=True)
    df["will_order_next_30d"] = df["will_order_next_30d"].astype(int)
    df = df.sort_values(["snapshot_date", "user_id"]).reset_index(drop=True)

    non_feature_cols = {"user_id", "snapshot_date", "will_order_next_30d"}
    numeric_features = [
        col
        for col in df.columns
        if col not in non_feature_cols and pd.api.types.is_numeric_dtype(df[col])
    ]
    if not numeric_features:
        raise RuntimeError("No numeric features available for training.")

    train_df, val_df, test_df = split_by_snapshot(df)
    X_train = train_df[numeric_features]
    y_train = train_df["will_order_next_30d"]
    X_val = val_df[numeric_features]
    y_val = val_df["will_order_next_30d"]
    X_test = test_df[numeric_features]
    y_test = test_df["will_order_next_30d"]

    selected_features = select_features(
        X_train,
        y_train,
        X_val,
        y_val,
        max_features=args.max_features,
    )
    X_train_sel = X_train[selected_features]
    X_val_sel = X_val[selected_features]
    X_test_sel = X_test[selected_features]

    candidates: dict[str, Pipeline] = {
        "logistic_regression": Pipeline(
            steps=[
                ("imputer", SimpleImputer(strategy="median")),
                ("scaler", StandardScaler()),
                (
                    "clf",
                    LogisticRegression(
                        max_iter=3000,
                        class_weight="balanced",
                        solver="lbfgs",
                    ),
                ),
            ]
        ),
        "random_forest": Pipeline(
            steps=[
                ("imputer", SimpleImputer(strategy="median")),
                (
                    "clf",
                    RandomForestClassifier(
                        n_estimators=500,
                        max_depth=10,
                        min_samples_leaf=8,
                        random_state=42,
                        n_jobs=-1,
                        class_weight="balanced_subsample",
                    ),
                ),
            ]
        ),
    }

    model_results: dict[str, dict[str, Any]] = {}
    for name, pipeline in candidates.items():
        pipeline.fit(X_train_sel, y_train)
        val_scores = pipeline.predict_proba(X_val_sel)[:, 1]
        model_results[name] = {
            "model": pipeline,
            "val_roc_auc": safe_roc_auc(y_val, val_scores),
            "val_pr_auc": safe_pr_auc(y_val, val_scores),
        }

    best_name = sorted(
        model_results.keys(),
        key=lambda key: (
            model_results[key]["val_pr_auc"],
            model_results[key]["val_roc_auc"],
        ),
        reverse=True,
    )[0]
    best_model: Pipeline = model_results[best_name]["model"]

    val_scores_best = best_model.predict_proba(X_val_sel)[:, 1]
    threshold = compute_threshold(y_val, val_scores_best)
    test_scores = best_model.predict_proba(X_test_sel)[:, 1]
    test_metrics = evaluate_predictions(y_test, test_scores, threshold=threshold)
    val_metrics = evaluate_predictions(y_val, val_scores_best, threshold=threshold)

    feature_importance = get_feature_importance(best_model, selected_features)

    score_bins = np.linspace(0.0, 1.0, 11)
    expected_counts, _ = np.histogram(test_scores, bins=score_bins)
    expected_dist = (expected_counts / max(1, expected_counts.sum())).tolist()

    model_version = datetime.now(UTC).strftime("v%Y%m%d%H%M%S")
    artifact = {
        "model": best_model,
        "selected_features": selected_features,
        "threshold": threshold,
        "model_name": "sliceiq_reorder_propensity",
        "model_version": model_version,
        "trained_at_utc": datetime.now(UTC).isoformat(),
    }

    model_output = Path(args.model_output)
    model_output.parent.mkdir(parents=True, exist_ok=True)
    joblib.dump(artifact, model_output)

    metrics_payload = {
        "model_name": artifact["model_name"],
        "model_version": model_version,
        "selected_feature_count": len(selected_features),
        "selected_features": selected_features,
        "best_model_family": best_name,
        "threshold": threshold,
        "dataset_rows": len(df),
        "train_rows": len(train_df),
        "val_rows": len(val_df),
        "test_rows": len(test_df),
        "class_balance": {
            "train_positive_rate": float(y_train.mean()),
            "val_positive_rate": float(y_val.mean()),
            "test_positive_rate": float(y_test.mean()),
        },
        "validation_metrics": val_metrics,
        "test_metrics": test_metrics,
        "candidate_validation_scores": {
            name: {
                "val_roc_auc": result["val_roc_auc"],
                "val_pr_auc": result["val_pr_auc"],
            }
            for name, result in model_results.items()
        },
        "snapshot_split": {
            "train_start": train_df["snapshot_date"].min().isoformat(),
            "train_end": train_df["snapshot_date"].max().isoformat(),
            "val_start": val_df["snapshot_date"].min().isoformat(),
            "val_end": val_df["snapshot_date"].max().isoformat(),
            "test_start": test_df["snapshot_date"].min().isoformat(),
            "test_end": test_df["snapshot_date"].max().isoformat(),
        },
        "score_distribution_baseline": {
            "bin_edges": score_bins.tolist(),
            "test_distribution": expected_dist,
            "test_mean_score": float(np.mean(test_scores)),
            "test_std_score": float(np.std(test_scores)),
        },
        "trained_at_utc": datetime.now(UTC).isoformat(),
    }

    metrics_output = Path(args.metrics_output)
    metrics_output.parent.mkdir(parents=True, exist_ok=True)
    metrics_output.write_text(json.dumps(metrics_payload, indent=2), encoding="utf-8")

    feature_imp_output = Path(args.feature_importance_output)
    feature_imp_output.parent.mkdir(parents=True, exist_ok=True)
    feature_importance.to_csv(feature_imp_output, index=False)

    drift_baseline_payload = {
        "model_name": artifact["model_name"],
        "model_version": model_version,
        "generated_at_utc": datetime.now(UTC).isoformat(),
        "bin_edges": score_bins.tolist(),
        "test_distribution": expected_dist,
        "test_mean_score": float(np.mean(test_scores)),
        "test_std_score": float(np.std(test_scores)),
        "threshold": threshold,
    }
    drift_baseline_output = Path(args.drift_baseline_output)
    drift_baseline_output.parent.mkdir(parents=True, exist_ok=True)
    drift_baseline_output.write_text(json.dumps(drift_baseline_payload, indent=2), encoding="utf-8")

    print(f"[done] best_model={best_name} threshold={threshold:.4f}")
    print(f"[done] model artifact: {model_output}")
    print(f"[done] metrics: {metrics_output}")
    print(f"[done] feature importances: {feature_imp_output}")
    print(f"[done] drift baseline: {drift_baseline_output}")


if __name__ == "__main__":
    main()
