import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SocketProvider } from "./providers/SocketProvider";
import { LiveStatus } from "./components/LiveStatus";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <SocketProvider>
            <div className="mx-auto flex max-w-5xl items-center justify-between px-6 py-4">
              <div className="text-sm font-semibold">SliceIQ</div>
              <LiveStatus />
            </div>
            {children}
          </SocketProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
